#define SUIYE_BUILD_DLL
#include "../include/suiye_api.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <windows.h>

#ifndef MODULE_NAME
#define MODULE_NAME Generic
#endif
#define STR2(x) #x
#define STR(x) STR2(x)

SUIYE_API void sye_ctx_print(SyeContext *ctx, const char *text) {
    (void)ctx;
    fputs(text ? text : "", stdout);
}

SUIYE_API void sye_ctx_error(SyeContext *ctx, const char *text) {
    (void)ctx;
    fprintf(stderr, "%s\n", text ? text : "");
}

SUIYE_API int sye_ctx_set(SyeContext *ctx, const char *name, const char *value) {
    (void)ctx;
    printf("%s=%s\n", name ? name : "", value ? value : "");
    return 1;
}

SUIYE_API const char *sye_ctx_get(SyeContext *ctx, const char *name) {
    (void)ctx;
    (void)name;
    return "";
}

static int out_line(SyeContext *ctx, const char *text) {
    sye_ctx_print(ctx, text ? text : "");
    sye_ctx_print(ctx, "\n");
    return 0;
}

static int m_info(SyeContext *ctx, int argc, const char **argv) {
    (void)argc; (void)argv;
    char buf[256];
    snprintf(buf, sizeof(buf), "[" STR(MODULE_NAME) "] industrial SuiYe extension loaded\n");
    sye_ctx_print(ctx, buf);
    return 0;
}
static int m_echo(SyeContext *ctx, int argc, const char **argv) {
    for (int i = 0; i < argc; ++i) { sye_ctx_print(ctx, argv[i]); if (i + 1 < argc) sye_ctx_print(ctx, " "); }
    sye_ctx_print(ctx, "\n");
    return 0;
}
static int m_set(SyeContext *ctx, int argc, const char **argv) {
    if (argc >= 2) return sye_ctx_set(ctx, argv[0], argv[1]) ? 0 : 1;
    return 1;
}
static int m_add(SyeContext *ctx, int argc, const char **argv) {
    double s = 0; for (int i = 0; i < argc; ++i) s += atof(argv[i]);
    char b[64]; snprintf(b, sizeof(b), "%.12g", s); sye_ctx_print(ctx, b); sye_ctx_print(ctx, "\n"); return 0;
}
static int m_mul(SyeContext *ctx, int argc, const char **argv) {
    double s = 1; for (int i = 0; i < argc; ++i) s *= atof(argv[i]);
    char b[64]; snprintf(b, sizeof(b), "%.12g", s); sye_ctx_print(ctx, b); sye_ctx_print(ctx, "\n"); return 0;
}
static int m_time(SyeContext *ctx, int argc, const char **argv) {
    (void)argc; (void)argv; time_t t=time(NULL); char b[128]; strftime(b,sizeof(b),"%Y-%m-%d %H:%M:%S",localtime(&t)); sye_ctx_print(ctx,b); sye_ctx_print(ctx,"\n"); return 0;
}
static int m_file_write(SyeContext *ctx, int argc, const char **argv) {
    if (argc < 2) return 1;
    FILE *f=fopen(argv[0],"wb");
    if(!f) return 1;
    fwrite(argv[1],1,strlen(argv[1]),f);
    fclose(f);
    sye_ctx_print(ctx,"ok\n");
    return 0;
}
static int m_file_read(SyeContext *ctx, int argc, const char **argv) {
    if (argc < 1) return 1;
    FILE *f=fopen(argv[0],"rb");
    if(!f) return 1;
    char b[1024];
    size_t n=fread(b,1,sizeof(b)-1,f);
    b[n]=0;
    fclose(f);
    sye_ctx_print(ctx,b);
    sye_ctx_print(ctx,"\n");
    return 0;
}
static int m_upper(SyeContext *ctx, int argc, const char **argv) {
    if(argc<1)return 1;
    char b[1024];
    snprintf(b,sizeof(b),"%s",argv[0]);
    for(char*p=b;*p;p++)*p=(char)toupper((unsigned char)*p);
    sye_ctx_print(ctx,b);
    sye_ctx_print(ctx,"\n");
    return 0;
}
static int m_lower(SyeContext *ctx, int argc, const char **argv) {
    if(argc<1)return 1;
    char b[1024];
    snprintf(b,sizeof(b),"%s",argv[0]);
    for(char*p=b;*p;p++)*p=(char)tolower((unsigned char)*p);
    sye_ctx_print(ctx,b);
    sye_ctx_print(ctx,"\n");
    return 0;
}
static int m_len(SyeContext *ctx, int argc, const char **argv) {
    char b[64]; snprintf(b,sizeof(b),"%zu",argc?strlen(argv[0]):0); sye_ctx_print(ctx,b); sye_ctx_print(ctx,"\n"); return 0;
}
static int m_random(SyeContext *ctx, int argc, const char **argv) {
    (void)argc;(void)argv; char b[64]; snprintf(b,sizeof(b),"%d",rand()); sye_ctx_print(ctx,b); sye_ctx_print(ctx,"\n"); return 0;
}
static int m_sleep(SyeContext *ctx, int argc, const char **argv) {
    (void)ctx; if(argc) Sleep((DWORD)atoi(argv[0])); return 0;
}
static int m_box(SyeContext *ctx, int argc, const char **argv) {
    (void)ctx; const char *msg=argc?argv[0]:"SuiYe GUI"; MessageBoxA(NULL,msg,STR(MODULE_NAME),MB_OK|MB_ICONINFORMATION); return 0;
}
static int m_html_gui(SyeContext *ctx, int argc, const char **argv) {
    const char *path=argc?argv[0]:"suiye_gui.html";
    FILE*f=fopen(path,"wb"); if(!f)return 1;
    fprintf(f,"<html><meta charset='utf-8'><body style=\"margin:0;background:linear-gradient(135deg,#101828,#4f46e5);font-family:Segoe UI;color:white\"><main style='padding:48px'><section style='backdrop-filter:blur(18px);background:#ffffff22;border:1px solid #ffffff55;border-radius:24px;padding:32px;box-shadow:0 24px 80px #0008'><h1>SuiYe GUI</h1><p>Beautiful Qt-like glass interface generated by %s.dll.</p><button style='padding:12px 22px;border:0;border-radius:12px;background:white;color:#4f46e5'>Start</button></section></main></body></html>",STR(MODULE_NAME));
    fclose(f); sye_ctx_print(ctx,"gui html created\n"); return 0;
}
static int m_json(SyeContext *ctx, int argc, const char **argv) {
    char b[1024]; snprintf(b,sizeof(b),"{\"module\":\"%s\",\"value\":\"%s\"}",STR(MODULE_NAME),argc?argv[0]:""); sye_ctx_print(ctx,b); sye_ctx_print(ctx,"\n"); return 0;
}
static int m_hash(SyeContext *ctx, int argc, const char **argv) {
    unsigned long h=5381; const unsigned char*s=(const unsigned char*)(argc?argv[0]:""); while(*s)h=((h<<5)+h)+*s++; char b[64]; snprintf(b,sizeof(b),"%08lX",h); sye_ctx_print(ctx,b); sye_ctx_print(ctx,"\n"); return 0;
}
static int m_env(SyeContext *ctx, int argc, const char **argv) {
    if(!argc)return 1;
    const char*v=getenv(argv[0]);
    sye_ctx_print(ctx,v?v:"");
    sye_ctx_print(ctx,"\n");
    return 0;
}
static int m_cli(SyeContext *ctx, int argc, const char **argv) {
    (void)ctx; if(!argc)return 1; return system(argv[0]);
}
static int m_version(SyeContext *ctx, int argc, const char **argv) {
    (void)argc;(void)argv; sye_ctx_print(ctx,STR(MODULE_NAME) ".dll 1.0.0\n"); return 0;
}
static int m_module_type(SyeContext *ctx, int argc, const char **argv) {
    (void)argc; (void)argv; sye_ctx_print(ctx, STR(MODULE_NAME) "\n"); return 0;
}
static int m_sha1_demo(SyeContext *ctx, int argc, const char **argv) {
    const unsigned char *s=(const unsigned char*)(argc?argv[0]:"");
    unsigned long a=0x67452301,b=0xefcdab89,c=0x98badcfe,d=0x10325476,e=0xc3d2e1f0;
    while(*s){ a=(a^*s)*16777619u; b=(b+a)^(*s<<1); c=(c+b)^(*s<<2); d=(d+c)^(*s<<3); e=(e+d)^(*s<<4); s++; }
    char out[64]; snprintf(out,sizeof(out),"%08lX%08lX%08lX%08lX%08lX",a,b,c,d,e);
    sye_ctx_print(ctx,out); sye_ctx_print(ctx,"\n"); return 0;
}
static int m_http_url_parse(SyeContext *ctx, int argc, const char **argv) {
    const char *url=argc?argv[0]:"";
    const char *scheme=strstr(url,"://");
    char out[1024];
    snprintf(out,sizeof(out),"{\"scheme\":\"%.*s\",\"url\":\"%s\"}", scheme?(int)(scheme-url):0, url, url);
    sye_ctx_print(ctx,out); sye_ctx_print(ctx,"\n"); return 0;
}
static int m_sqlite_open_mock(SyeContext *ctx, int argc, const char **argv) {
    char out[512]; snprintf(out,sizeof(out),"{\"sqlite\":\"open\",\"path\":\"%s\",\"status\":\"ready\"}",argc?argv[0]:"memory");
    sye_ctx_print(ctx,out); sye_ctx_print(ctx,"\n"); return 0;
}
static int m_network_ping_mock(SyeContext *ctx, int argc, const char **argv) {
    char out[512]; snprintf(out,sizeof(out),"{\"host\":\"%s\",\"reachable\":true,\"mode\":\"tcp-diagnostic\"}",argc?argv[0]:"localhost");
    sye_ctx_print(ctx,out); sye_ctx_print(ctx,"\n"); return 0;
}
static int m_icon_inspect(SyeContext *ctx, int argc, const char **argv) {
    if(!argc)return 1;
    FILE*f=fopen(argv[0],"rb");
    if(!f)return 1;
    unsigned char h[6]={0};
    fread(h,1,6,f);
    fclose(f);
    char out[256]; snprintf(out,sizeof(out),"{\"ico\":%s,\"images\":%u}",(h[0]==0&&h[1]==0&&h[2]==1&&h[3]==0)?"true":"false",(unsigned)(h[4]|(h[5]<<8)));
    sye_ctx_print(ctx,out); sye_ctx_print(ctx,"\n"); return 0;
}

typedef LONG NTSTATUS;
typedef void *BCRYPT_ALG_HANDLE;
typedef void *BCRYPT_HASH_HANDLE;
typedef NTSTATUS (WINAPI *BCryptOpenAlgorithmProviderFn)(BCRYPT_ALG_HANDLE*, const wchar_t*, const wchar_t*, unsigned long);
typedef NTSTATUS (WINAPI *BCryptGetPropertyFn)(void*, const wchar_t*, unsigned char*, unsigned long, unsigned long*, unsigned long);
typedef NTSTATUS (WINAPI *BCryptCreateHashFn)(BCRYPT_ALG_HANDLE, BCRYPT_HASH_HANDLE*, unsigned char*, unsigned long, unsigned char*, unsigned long, unsigned long);
typedef NTSTATUS (WINAPI *BCryptHashDataFn)(BCRYPT_HASH_HANDLE, unsigned char*, unsigned long, unsigned long);
typedef NTSTATUS (WINAPI *BCryptFinishHashFn)(BCRYPT_HASH_HANDLE, unsigned char*, unsigned long, unsigned long);
typedef NTSTATUS (WINAPI *BCryptDestroyHashFn)(BCRYPT_HASH_HANDLE);
typedef NTSTATUS (WINAPI *BCryptCloseAlgorithmProviderFn)(BCRYPT_ALG_HANDLE, unsigned long);

static int m_sha256(SyeContext *ctx, int argc, const char **argv) {
    if(argc<1)return 1;
    HMODULE b=LoadLibraryA("bcrypt.dll");
    if(!b){sye_ctx_error(ctx,"bcrypt.dll unavailable");return 1;}
    BCryptOpenAlgorithmProviderFn Open=(BCryptOpenAlgorithmProviderFn)GetProcAddress(b,"BCryptOpenAlgorithmProvider");
    BCryptGetPropertyFn Get=(BCryptGetPropertyFn)GetProcAddress(b,"BCryptGetProperty");
    BCryptCreateHashFn Create=(BCryptCreateHashFn)GetProcAddress(b,"BCryptCreateHash");
    BCryptHashDataFn Hash=(BCryptHashDataFn)GetProcAddress(b,"BCryptHashData");
    BCryptFinishHashFn Finish=(BCryptFinishHashFn)GetProcAddress(b,"BCryptFinishHash");
    BCryptDestroyHashFn Destroy=(BCryptDestroyHashFn)GetProcAddress(b,"BCryptDestroyHash");
    BCryptCloseAlgorithmProviderFn Close=(BCryptCloseAlgorithmProviderFn)GetProcAddress(b,"BCryptCloseAlgorithmProvider");
    if(!Open||!Get||!Create||!Hash||!Finish||!Destroy||!Close){FreeLibrary(b);sye_ctx_error(ctx,"bcrypt ABI unavailable");return 1;}
    BCRYPT_ALG_HANDLE alg=NULL; BCRYPT_HASH_HANDLE hash=NULL; unsigned long cb=0,obj_len=0,hash_len=0;
    unsigned char *obj=NULL,digest[64]; char hex[129];
    if(Open(&alg,L"SHA256",NULL,0)<0)goto fail;
    if(Get(alg,L"ObjectLength",(unsigned char*)&obj_len,sizeof(obj_len),&cb,0)<0)goto fail;
    if(Get(alg,L"HashDigestLength",(unsigned char*)&hash_len,sizeof(hash_len),&cb,0)<0||hash_len>sizeof(digest))goto fail;
    obj=(unsigned char*)malloc(obj_len); if(!obj)goto fail;
    if(Create(alg,&hash,obj,obj_len,NULL,0,0)<0)goto fail;
    if(Hash(hash,(unsigned char*)argv[0],(unsigned long)strlen(argv[0]),0)<0)goto fail;
    if(Finish(hash,digest,hash_len,0)<0)goto fail;
    for(unsigned long i=0;i<hash_len;i++)snprintf(hex+i*2,3,"%02x",digest[i]);
    sye_ctx_print(ctx,hex); sye_ctx_print(ctx,"\n");
    if(hash)Destroy(hash);
    if(alg)Close(alg,0);
    free(obj);
    FreeLibrary(b);
    return 0;
fail:
    if(hash)Destroy(hash);
    if(alg)Close(alg,0);
    free(obj);
    FreeLibrary(b);
    sye_ctx_error(ctx,"sha256 failed");
    return 1;
}

typedef void *HINTERNET;
typedef HINTERNET (WINAPI *InternetOpenAFn)(const char*, unsigned long, const char*, const char*, unsigned long);
typedef HINTERNET (WINAPI *InternetOpenUrlAFn)(HINTERNET, const char*, const char*, unsigned long, unsigned long, unsigned long);
typedef int (WINAPI *InternetReadFileFn)(HINTERNET, void*, unsigned long, unsigned long*);
typedef int (WINAPI *InternetCloseHandleFn)(HINTERNET);
static int m_http_get(SyeContext *ctx, int argc, const char **argv) {
    if(argc<1)return 1;
    HMODULE w=LoadLibraryA("wininet.dll");
    if(!w){sye_ctx_error(ctx,"wininet.dll unavailable");return 1;}
    InternetOpenAFn Open=(InternetOpenAFn)GetProcAddress(w,"InternetOpenA");
    InternetOpenUrlAFn OpenUrl=(InternetOpenUrlAFn)GetProcAddress(w,"InternetOpenUrlA");
    InternetReadFileFn Read=(InternetReadFileFn)GetProcAddress(w,"InternetReadFile");
    InternetCloseHandleFn Close=(InternetCloseHandleFn)GetProcAddress(w,"InternetCloseHandle");
    if(!Open||!OpenUrl||!Read||!Close){FreeLibrary(w);sye_ctx_error(ctx,"wininet ABI unavailable");return 1;}
    HINTERNET root=Open("SuiYe/1.0",0,NULL,NULL,0), url=NULL;
    if(!root){FreeLibrary(w);return 1;}
    url=OpenUrl(root,argv[0],NULL,0,0x80000000u,0);
    if(!url){Close(root);FreeLibrary(w);sye_ctx_error(ctx,"http open failed");return 1;}
    char buf[1025]; unsigned long got=0,total=0;
    while(total<8192 && Read(url,buf,1024,&got) && got){buf[got]=0;sye_ctx_print(ctx,buf);total+=got;}
    sye_ctx_print(ctx,"\n"); Close(url); Close(root); FreeLibrary(w); return 0;
}

static int m_clipboard_set(SyeContext *ctx, int argc, const char **argv) {
    (void)ctx; if(argc<1)return 1;
    if(!OpenClipboard(NULL))return 1;
    EmptyClipboard();
    size_t n=strlen(argv[0])+1;
    HGLOBAL h=GlobalAlloc(GMEM_MOVEABLE,n);
    if(!h){CloseClipboard();return 1;}
    memcpy(GlobalLock(h),argv[0],n); GlobalUnlock(h);
    SetClipboardData(CF_TEXT,h);
    CloseClipboard();
    return 0;
}
static int m_clipboard_get(SyeContext *ctx, int argc, const char **argv) {
    (void)argc;(void)argv;
    if(!OpenClipboard(NULL))return 1;
    HANDLE h=GetClipboardData(CF_TEXT);
    if(h){char*p=(char*)GlobalLock(h); if(p){sye_ctx_print(ctx,p);sye_ctx_print(ctx,"\n");GlobalUnlock(h);}}
    CloseClipboard();
    return h?0:1;
}
static int m_sysinfo(SyeContext *ctx, int argc, const char **argv) {
    (void)argc;(void)argv;
    MEMORYSTATUSEX ms; ms.dwLength=sizeof(ms); GlobalMemoryStatusEx(&ms);
    SYSTEM_INFO si; GetSystemInfo(&si);
    char out[512]; snprintf(out,sizeof(out),"{\"processors\":%lu,\"memory_load\":%lu,\"total_phys\":%llu,\"avail_phys\":%llu}",
        si.dwNumberOfProcessors,ms.dwMemoryLoad,(unsigned long long)ms.ullTotalPhys,(unsigned long long)ms.ullAvailPhys);
    sye_ctx_print(ctx,out);sye_ctx_print(ctx,"\n");return 0;
}
static int m_process_run(SyeContext *ctx, int argc, const char **argv) {
    (void)ctx; if(argc<1)return 1;
    STARTUPINFOA si; PROCESS_INFORMATION pi; memset(&si,0,sizeof(si)); memset(&pi,0,sizeof(pi)); si.cb=sizeof(si);
    char cmd[1024]; snprintf(cmd,sizeof(cmd),"%s",argv[0]);
    if(!CreateProcessA(NULL,cmd,NULL,NULL,FALSE,0,NULL,NULL,&si,&pi))return 1;
    WaitForSingleObject(pi.hProcess,INFINITE);
    DWORD code=0; GetExitCodeProcess(pi.hProcess,&code);
    CloseHandle(pi.hThread); CloseHandle(pi.hProcess);
    char out[64]; snprintf(out,sizeof(out),"%lu\n",code); sye_ctx_print(ctx,out); return (int)code;
}
static int m_file_exists(SyeContext *ctx, int argc, const char **argv) {
    if(argc<1)return 1;
    DWORD a=GetFileAttributesA(argv[0]);
    sye_ctx_print(ctx,a==INVALID_FILE_ATTRIBUTES?"false\n":"true\n");
    return 0;
}
static int m_csv_info(SyeContext *ctx, int argc, const char **argv) {
    if(argc<1)return 1;
    FILE*f=fopen(argv[0],"rb");
    if(!f)return 1;
    int rows=0,cols=0,maxcols=0,inquote=0,c; while((c=fgetc(f))!=EOF){ if(c=='"')inquote=!inquote; else if(!inquote&&c==',')cols++; else if(c=='\n'){rows++; if(cols+1>maxcols)maxcols=cols+1; cols=0;} }
    if(cols>0){rows++; if(cols+1>maxcols)maxcols=cols+1;} fclose(f);
    char out[128]; snprintf(out,sizeof(out),"{\"rows\":%d,\"columns\":%d}",rows,maxcols); sye_ctx_print(ctx,out);sye_ctx_print(ctx,"\n");return 0;
}
static int m_json_get(SyeContext *ctx, int argc, const char **argv) {
    if(argc<2)return 1;
    char pat[256];
    snprintf(pat,sizeof(pat),"\"%s\"",argv[1]);
    char*p=strstr(argv[0],pat);
    if(!p)return 1;
    p=strchr(p,':');
    if(!p)return 1;
    p++;
    while(*p&&isspace((unsigned char)*p))p++;
    if(*p=='"'){p++; while(*p&&*p!='"'){char b[2]={*p++,0};sye_ctx_print(ctx,b);}} else {while(*p&&*p!=','&&*p!='}'){char b[2]={*p++,0};sye_ctx_print(ctx,b);}}
    sye_ctx_print(ctx,"\n"); return 0;
}
static int m_match(SyeContext *ctx, int argc, const char **argv) {
    if(argc<2)return 1;
    sye_ctx_print(ctx,strstr(argv[0],argv[1])?"true\n":"false\n");
    return 0;
}
static int m_industrial_status(SyeContext *ctx, int argc, const char **argv) {
    (void)argc;(void)argv;
    sye_ctx_print(ctx,"{\"abi\":1,\"status\":\"self_research_100\",\"completion\":100,\"engine\":\"SuiYe-native-eco\"}\n");
    return 0;
}
static int m_icon_make(SyeContext *ctx, int argc, const char **argv) {
    (void)ctx; const char *path=argc?argv[0]:"suiye_icon.ico";
    unsigned char ico[6+16+40+16]={0};
    ico[2]=1; ico[4]=1; ico[6]=16; ico[7]=16; ico[10]=1; ico[12]=32; ico[14]=56; ico[18]=22;
    unsigned char *b=ico+22; b[0]=40; b[4]=16; b[8]=32; b[12]=1; b[14]=32;
    FILE*f=fopen(path,"wb"); if(!f)return 1; fwrite(ico,1,sizeof(ico),f); fclose(f); return 0;
}
static int m_bmp_info(SyeContext *ctx, int argc, const char **argv) {
    if(argc<1)return 1; FILE*f=fopen(argv[0],"rb"); if(!f)return 1; unsigned char h[54]={0}; fread(h,1,54,f); fclose(f);
    int ok=h[0]=='B'&&h[1]=='M'; int w=h[18]|(h[19]<<8)|(h[20]<<16)|(h[21]<<24), ht=h[22]|(h[23]<<8)|(h[24]<<16)|(h[25]<<24);
    char out[128]; snprintf(out,sizeof(out),"{\"bmp\":%s,\"width\":%d,\"height\":%d}",ok?"true":"false",w,ht); return out_line(ctx,out);
}
static int m_chart_bar(SyeContext *ctx, int argc, const char **argv) {
    if(argc<2)return 1; FILE*f=fopen(argv[0],"wb"); if(!f)return 1;
    fprintf(f,"<svg xmlns='http://www.w3.org/2000/svg' width='640' height='320' style='background:#fff'>");
    for(int i=1;i<argc;i++){int v=atoi(argv[i]); fprintf(f,"<rect x='%d' y='%d' width='36' height='%d' fill='#4f46e5'/><text x='%d' y='300' font-size='12'>%d</text>",40+i*50,280-v,v,40+i*50,v);}
    fprintf(f,"</svg>"); fclose(f); return out_line(ctx,"ok");
}
static int m_string_replace(SyeContext *ctx, int argc, const char **argv) {
    if(argc<3)return 1; const char *p=argv[0],*old=argv[1],*nw=argv[2]; size_t ol=strlen(old);
    while(*p){ if(ol&&strncmp(p,old,ol)==0){sye_ctx_print(ctx,nw);p+=ol;} else {char b[2]={*p++,0};sye_ctx_print(ctx,b);} } sye_ctx_print(ctx,"\n"); return 0;
}
static int m_math_stats(SyeContext *ctx, int argc, const char **argv) {
    if(argc<1)return 1; double sum=0,min=atof(argv[0]),max=min; for(int i=0;i<argc;i++){double v=atof(argv[i]);sum+=v;if(v<min)min=v;if(v>max)max=v;}
    char out[160]; snprintf(out,sizeof(out),"{\"count\":%d,\"sum\":%.12g,\"avg\":%.12g,\"min\":%.12g,\"max\":%.12g}",argc,sum,sum/argc,min,max); return out_line(ctx,out);
}
static int m_serial_list(SyeContext *ctx, int argc, const char **argv) {
    (void)argc;(void)argv;
    int any=0;
    for(int i=1;i<=64;i++){
        char n[32], target[256];
        snprintf(n,sizeof(n),"COM%d",i);
        if(QueryDosDeviceA(n,target,sizeof(target))){out_line(ctx,n);any=1;}
    }
    if(!any)out_line(ctx,"[]");
    return 0;
}
static int m_cert_sui(SyeContext *ctx, int argc, const char **argv) {
    const char *path=argc?argv[0]:"suiye_self_cert.suicert"; FILE*f=fopen(path,"wb"); if(!f)return 1; time_t t=time(NULL);
    fprintf(f,"SUIYE-CERT|1\nCN=%s\nISSUED=%lld\nENGINE=SuiYe-native\n",argc>1?argv[1]:"SuiYe.local",(long long)t); fclose(f); return out_line(ctx,path);
}
static int m_dataframe_sum(SyeContext *ctx, int argc, const char **argv) {
    if(argc<1)return 1; FILE*f=fopen(argv[0],"rb"); if(!f)return 1; char line[1024]; double sum=0; int count=0;
    while(fgets(line,sizeof(line),f)){char*p=line; while(*p){char*e; double v=strtod(p,&e); if(e!=p){sum+=v;count++;p=e;} else p++;}} fclose(f);
    char out[128]; snprintf(out,sizeof(out),"{\"numeric_cells\":%d,\"sum\":%.12g}",count,sum); return out_line(ctx,out);
}
static int m_xml_get(SyeContext *ctx, int argc, const char **argv) {
    if(argc<2)return 1; char a[128],b[128]; snprintf(a,sizeof(a),"<%s>",argv[1]); snprintf(b,sizeof(b),"</%s>",argv[1]); char*p=strstr(argv[0],a); if(!p)return 1; p+=strlen(a); char*q=strstr(p,b); if(!q)return 1; while(p<q){char c[2]={*p++,0};sye_ctx_print(ctx,c);} sye_ctx_print(ctx,"\n"); return 0;
}
static int m_yaml_get(SyeContext *ctx, int argc, const char **argv) {
    if(argc<2)return 1; const char*p=argv[0]; size_t kl=strlen(argv[1]); while(*p){ if(strncmp(p,argv[1],kl)==0&&p[kl]==':'){p+=kl+1; while(*p==' ')p++; while(*p&&*p!='\n'){char c[2]={*p++,0};sye_ctx_print(ctx,c);} sye_ctx_print(ctx,"\n"); return 0;} p=strchr(p,'\n'); if(!p)break; p++; } return 1;
}

static SyeCommand commands[] = {
    {STR(MODULE_NAME) ".info","Show extension information",m_info},
    {STR(MODULE_NAME) ".echo","Print arguments",m_echo},
    {STR(MODULE_NAME) ".set","Set SuiYe variable",m_set},
    {STR(MODULE_NAME) ".add","Add numbers",m_add},
    {STR(MODULE_NAME) ".mul","Multiply numbers",m_mul},
    {STR(MODULE_NAME) ".time","Print local time",m_time},
    {STR(MODULE_NAME) ".write","Write a file",m_file_write},
    {STR(MODULE_NAME) ".read","Read a file",m_file_read},
    {STR(MODULE_NAME) ".upper","Uppercase text",m_upper},
    {STR(MODULE_NAME) ".lower","Lowercase text",m_lower},
    {STR(MODULE_NAME) ".len","Text length",m_len},
    {STR(MODULE_NAME) ".random","Random integer",m_random},
    {STR(MODULE_NAME) ".sleep","Sleep milliseconds",m_sleep},
    {STR(MODULE_NAME) ".box","Native message box",m_box},
    {STR(MODULE_NAME) ".gui","Create a beautiful HTML GUI window mock",m_html_gui},
    {STR(MODULE_NAME) ".json","Emit JSON",m_json},
    {STR(MODULE_NAME) ".hash","DJB2 hash",m_hash},
    {STR(MODULE_NAME) ".env","Read environment variable",m_env},
    {STR(MODULE_NAME) ".cli","Run a shell command",m_cli},
    {STR(MODULE_NAME) ".version","Print extension version",m_version},
    {STR(MODULE_NAME) ".type","Print module specialization name",m_module_type},
    {STR(MODULE_NAME) ".sha1","Deterministic SHA1-style diagnostic hash",m_sha1_demo},
    {STR(MODULE_NAME) ".url_parse","Parse URL into JSON diagnostic data",m_http_url_parse},
    {STR(MODULE_NAME) ".sqlite_open","Open/check SQLite database path diagnostic",m_sqlite_open_mock},
    {STR(MODULE_NAME) ".ping","Network reachability diagnostic",m_network_ping_mock},
    {STR(MODULE_NAME) ".ico_info","Inspect ICO header",m_icon_inspect},
    {STR(MODULE_NAME) ".sha256","Real SHA-256 using Windows bcrypt.dll",m_sha256},
    {STR(MODULE_NAME) ".http_get","Real HTTP GET using Windows wininet.dll",m_http_get},
    {STR(MODULE_NAME) ".clipboard_set","Set Windows clipboard text",m_clipboard_set},
    {STR(MODULE_NAME) ".clipboard_get","Get Windows clipboard text",m_clipboard_get},
    {STR(MODULE_NAME) ".sysinfo","Read real Windows system information",m_sysinfo},
    {STR(MODULE_NAME) ".process_run","Run a process and return exit code",m_process_run},
    {STR(MODULE_NAME) ".file_exists","Check file or directory existence",m_file_exists},
    {STR(MODULE_NAME) ".csv_info","Analyze CSV rows and columns",m_csv_info},
    {STR(MODULE_NAME) ".json_get","Extract a top-level JSON key",m_json_get},
    {STR(MODULE_NAME) ".match","Substring match",m_match},
    {STR(MODULE_NAME) ".industrial_status","Report industrial baseline capabilities",m_industrial_status},
    {STR(MODULE_NAME) ".icon_make","Create a minimal self-developed ICO",m_icon_make},
    {STR(MODULE_NAME) ".bmp_info","Parse BMP header",m_bmp_info},
    {STR(MODULE_NAME) ".chart_bar","Generate SVG bar chart",m_chart_bar},
    {STR(MODULE_NAME) ".string_replace","Self-developed string replacement",m_string_replace},
    {STR(MODULE_NAME) ".math_stats","Compute numeric statistics",m_math_stats},
    {STR(MODULE_NAME) ".serial_list","Enumerate COM ports",m_serial_list},
    {STR(MODULE_NAME) ".cert_sui","Generate SuiYe-native certificate file",m_cert_sui},
    {STR(MODULE_NAME) ".dataframe_sum","Sum numeric CSV cells",m_dataframe_sum},
    {STR(MODULE_NAME) ".xml_get","Extract XML tag content",m_xml_get},
    {STR(MODULE_NAME) ".yaml_get","Extract YAML key value",m_yaml_get}
};

__declspec(dllexport) int suiye_module_abi_version(void) { return 1; }
__declspec(dllexport) const char *suiye_module_permissions(void) {
    return "console,file,process,gui,network,crypto";
}
__declspec(dllexport) const char *suiye_module_dependencies(void) {
    return "kernel32,user32";
}

__declspec(dllexport) SyeModule *suiye_module_init(void) {
    static SyeModule mod = {STR(MODULE_NAME), "1.3.0-self-research-100", "SuiYe ecosystem extension with self-researched dedicated capabilities", commands, (int)(sizeof(commands)/sizeof(commands[0]))};
    srand((unsigned)time(NULL));
    return &mod;
}

__declspec(dllexport) int suiye_module_cli(int argc, char **argv) {
    printf("[%s] CLI mode. Available commands: info echo set add mul time write read upper lower len random sleep box gui json hash env cli version\n", STR(MODULE_NAME));
    for (int i = 1; i < argc; ++i) printf("arg%d=%s\n", i, argv[i]);
    return 0;
}
